#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

PURPLE='\033[0;35m'
CYAN='\033[0;36m'
NC='\033[0m' # No Color

echo -e "${PURPLE}Linting the src folder ==> ${NC}${CYAN}Ext: .js, .jsx${NC}"
npm run lint:fix
